### ISSUE TITLE
Aashray Reddy CSP Final Individual Review

### ISSUE THREAD

**Issue by KinetekEnergy** [KinetekEnergy/blog#3]
[Review](https://kinetekenergy.github.io/blog/posts/CSP-Final_IPYNB_2_/)
[Video](https://youtu.be/gd6uUlJ50Z0)

Or if you want to see the video on our deployed project: [Video on Project](https://napoleon-bonaparte-official.github.io/corsica-frontend/video?videoID=9)

Here is a post which combine all other posts we've made (checkpoints, etc.) into one if you want:
[Unified Post](https://kinetekenergy.github.io/blog/posts/Unfied-Post_IPYNB_2_/)

**Comment by tarunja1ks** [comment]
Component A:
Overall, very well done project as you included it clearly your response for each requirement however in the second response for the second data collection requirement I would try including a screenshot of your database to show proof for the requirement. You did very good on showing clearly all of your responses however another thing here you can add is link to the pull requests.

Component B:
Overall, your video was pretty good but you can be more specific on what the feature actually is an make it much more clear to any more viewers watching it. Great work on the login system and the update GUI for it as not many projects seemed to include something like that. 

Overall, I would score this a 4.91/5!!!
